version: 2

project_name: rcctl

before:
  hooks:
    - make build-installer INSTALLER_OUTPUT=install.yaml IMG={{ .Env.CONTROLLER_IMAGE }}:{{ .Version }} RUNNER_IMG={{ .Env.RUNNER_IMAGE }}:{{ .Version }}

builds:
  - id: rcctl
    main: ./cmd/rcctl
    binary: rcctl
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - ids:
      - rcctl
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  extra_files:
    - glob: install.yaml
