apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manager.yaml

images:
- name: controller
  newName: ghcr.io/nekomeowww/rc/controller
  newTag: dev-20260824-submodules
- name: runner
  newName: ghcr.io/nekomeowww/rc/runner
  newTag: dev-20260824-submodules

configurations:
- kustomizeconfig.yaml
