---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - persistentvolumeclaims
  - pods
  - secrets
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - configs.rc.ayaka.io
  resources:
  - agentcredentials
  - credentials
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - configs.rc.ayaka.io
  resources:
  - agentcredentials/finalizers
  - credentials/finalizers
  verbs:
  - update
- apiGroups:
  - configs.rc.ayaka.io
  resources:
  - agentcredentials/status
  - credentials/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - repositories.rc.ayaka.io
  resources:
  - repositories
  - repositoryexecs
  - worktrees
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - repositories.rc.ayaka.io
  resources:
  - repositories/finalizers
  - repositoryexecs/finalizers
  - worktrees/finalizers
  verbs:
  - update
- apiGroups:
  - repositories.rc.ayaka.io
  resources:
  - repositories/status
  - repositoryexecs/status
  - worktrees/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - workspaces.rc.ayaka.io
  resources:
  - agentprocesses
  - workspaceenvironments
  - workspaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - workspaces.rc.ayaka.io
  resources:
  - agentprocesses/finalizers
  - workspaceenvironments/finalizers
  - workspaces/finalizers
  verbs:
  - update
- apiGroups:
  - workspaces.rc.ayaka.io
  resources:
  - agentprocesses/status
  - workspaceenvironments/status
  - workspaces/status
  verbs:
  - get
  - patch
  - update
