---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - configs.rc.ayaka.io
  resources:
  - agentcredentials
  - credentials
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - configs.rc.ayaka.io
  resources:
  - agentcredentials/finalizers
  - credentials/finalizers
  verbs:
  - update
- apiGroups:
  - configs.rc.ayaka.io
  resources:
  - agentcredentials/status
  - credentials/status
  verbs:
  - get
  - patch
  - update
