font pango:DejaVu Sans 10
output HEADLESS-1 mode 1280x720 position 0,0 bg #101827 solid_color
seat seat0 fallback true
default_border pixel 2
focus_follows_mouse no
workspace 1 output HEADLESS-1
xwayland disable
