apiVersion: configs.rc.ayaka.io/v1alpha1
kind: Credential
metadata:
  labels:
    app.kubernetes.io/name: rc
    app.kubernetes.io/managed-by: kustomize
  name: credential-sample
spec:
  type: SSHPrivateKey
  secretKeyRef:
    name: git-ssh
    key: ssh-privatekey
