apiVersion: configs.rc.ayaka.io/v1alpha1
kind: AgentCredential
metadata:
  labels:
    app.kubernetes.io/name: rc
    app.kubernetes.io/managed-by: kustomize
  name: agentcredential-sample
spec:
  agent: codex
  secretKeyRef:
    name: codex-auth
    key: auth.json
