apiVersion: configs.rc.ayaka.io/v1alpha1
kind: Credential
metadata:
  labels:
    app.kubernetes.io/name: rc
    app.kubernetes.io/managed-by: kustomize
  name: credential-sample
spec:
  type: SSHPrivateKey
  sshPrivateKey:
    privateKeyRef:
      name: git-ssh
      key: ssh-privatekey
    knownHostsRef:
      name: git-ssh
      key: known_hosts
