## Append samples of your project ##
resources:
- configs_v1alpha1_agentcredential.yaml
- configs_v1alpha1_credential.yaml
- repositories_v1alpha1_repository.yaml
- repositories_v1alpha1_repositoryexec.yaml
- repositories_v1alpha1_worktree.yaml
- workspaces_v1alpha1_workspaceenvironment.yaml
- workspaces_v1alpha1_workspace.yaml
- workspaces_v1alpha1_agentprocess.yaml
- repositories_v1alpha1_worktreeexec.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
