apiVersion: workspaces.rc.ayaka.io/v1alpha1
kind: AgentProcess
metadata:
  labels:
    app.kubernetes.io/name: rc
    app.kubernetes.io/managed-by: kustomize
  name: agentprocess-sample
spec:
  targetRef:
    kind: Workspace
    name: workspace-sample
  command:
    - git
    - status
    - --short
  workingDirectory: /workspace/rc
  desiredState: Running
