apiVersion: workspaces.rc.ayaka.io/v1alpha1
kind: Workspace
metadata:
  labels:
    app.kubernetes.io/name: rc
    app.kubernetes.io/managed-by: kustomize
  name: workspace-sample
spec:
  desiredState: Running
  environmentRef:
    name: workspaceenvironment-sample
  mounts:
    - name: rc
      path: rc
      worktreeRef:
        name: worktree-sample
  defaultWorkingDirectory: /workspace/rc
  lifecycle:
    initialize:
      - command: ["git", "status", "--short"]
        workingDirectory: /workspace/rc
    beforeStop:
      - script: |
          printf 'Workspace runtime is stopping\n'
