# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/configs.rc.ayaka.io_agentcredentials.yaml
- bases/configs.rc.ayaka.io_credentials.yaml
- bases/repositories.rc.ayaka.io_repositories.yaml
- bases/repositories.rc.ayaka.io_repositoryexecs.yaml
- bases/repositories.rc.ayaka.io_worktrees.yaml
- bases/workspaces.rc.ayaka.io_workspaceenvironments.yaml
- bases/workspaces.rc.ayaka.io_workspaces.yaml
- bases/workspaces.rc.ayaka.io_agentprocesses.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [WEBHOOK] To enable webhook, uncomment the following section
# the following config is for teaching kustomize how to do kustomization for CRDs.
#configurations:
#- kustomizeconfig.yaml
